<?php
$cat_en_to_fr = array("rings" => "bagues",
					  "earrings" => "boucles-doreilles",
					  "pendants" => "pendentifs",
					  "necklaces" => "colliers",
					  "bracelets" => "bracelets",
					);

$cat_fr_to_en = array("bagues" => "rings",
					  "boucles-doreilles" => "earrings",
					  "pendentifs" => "pendants",
					  "colliers" =>  "necklaces",
					  "bracelets" => "bracelets",
					);

$en_subcategory_arr = array("diamond" 		   => "diamant",
				"half-eternity-diamond" 	   => "alliance-demi-tour-diamants",
				"full-eternity-diamond" 	   => "tour-complet-diamants",
				"solitaire-diamond" 		   => "solitaire",
				"gems" 					   => "pierre-de-couleur",
				"pearls" 					   => "perles",
				"gems-and-diamond" 		   => "diamant-et-pierre-de-couleur",
				"pearls-and-diamond" 		   => "diamant-et-perles",
				"diamond-earrings" 				   => "boucles-doreilles-diamant",
				"gems-earrings" 				   => "boucles-doreilles-pierre-de-couleur",
				"pearls-earrings" 				   => "boucles-doreilles-perles",
				"gems-and-diamond-earrings" 	   => "boucles-doreilles-diamant-et-pierre-de-couleur",
				"pearls-and-diamond-earrings" 	   => "boucles-doreilles-diamant-et-perles",
				"diamond-pendant"				   => "pendentif-diamant",
				"gems-pendant" 					   => "pendentif-pierre-de-couleur",
				"pearls-pendant" 				   => "pendentif-perles",
				"gems-and-diamond pendant" 		   => "pendentif-diamant-et-pierre-de-couleur",
				"pearls-and-diamond-pendant"	   => "pendentif-diamant-et-perles",
				"diamond-necklace" 				   => "collier-diamant",
				"gems-necklace" 				   => "collier-pierre-de-couleur",
				"pearls-necklace" 				   => "collier-perles",
				"gems-and-diamond-necklace" 	   => "collier-diamant-et-pierre-de-couleur",
				"pearls-and-diamond-necklace" 	   => "collier-diamant-et-perles",
				"diamond-bracelet" 				   => "bracelet-diamant",
				"gems-bracelet" 				   => "bracelet-pierre-de-couleur",
				"pearls-bracelet" 				   => "bracelet-perles",
				"gems-and-diamond-bracelet" 	   => "bracelet-diamant-et-pierre-de-couleur",
				"pearls-and-diamond-bracelet"      => "bracelet-diamant-et-perles",
				"pearls-and-colored-stone"    => "pierre-de-couleur-et-perles",
				"pearl-and-colored-stone"  => "pierre-de-couleur et perles",
				"pearl-and-colored-stone"  => "pierre-de-couleur-et-perles",
				"pearl-and-colored-stone" => "pierre-de-couleur-et-perles",
				"pearl-and-colored-stone" => "pierre-de-couleur-et-perles",
				"pieces-in-gold-without-any-stone" => "pièce-en-or-sans-pierre",
                );

$en_materials_arr = array("yellow-gold" => "or-jaune",
					      "white-gold"  => "or-blanc",
					      "pink-gold" => "or-rose",
					      "silver" => "argent",
					      "platinum" => "platinium",
					      "bi-colour-with-gold" => "bi-couleur-en-or",
 						  "three-colour-with-gold" => "trois-couleurs-dor",
 						  "black-metal" =>"métal-noir"
						 );

$fr_subcategory_arr = array("diamant" => "diamond",
					"alliance-demi-tour-diamants" => "half-eternity-diamond",
					"tour-complet-diamants"  => "full-eternity-diamond",
					"solitaire" => "solitaire-diamond",
					"pierre-de-couleur" => "gems",
					"diamant-et-pierre-de-couleur" => "gems-and-diamond",
					"perles" => "pearls",
					"diamant-et-pierre de couleur" => "gems-and-diamond",
					"diamant-et-perles" => "pearls-and-diamond",
					"boucles-doreilles-diamant" => "diamond-earrings",
					"boucles-doreilles-pierre-de-couleur" => "gems-earrings",
					"boucles-doreilles perles"  => "pearls-earrings",
					"boucles-doreilles-diamant-et-pierre-de-couleur" => "gems-and-diamond-earrings",
					"boucles-doreilles-diamant-et-perles" => "pearls-and-diamond-earrings",
					"pendentif-diamant"	 => "diamond-pendant",
					"pendentif-pierre-de-couleur"  => "gems-pendant",
					"pearls-pendant" => "Pendentif perles",
					"pendentif-diamant-et-pierre-de-couleur" => "gems-and-diamond pendant",
					"pendentif-diamant-et-perles" => "pearls-and-diamond-pendant",
					"collier-diamant" => "diamond-necklace",
					"collier-pierre-de-couleur" => "gems-necklace",
					"collier-perles" => "pearls-necklace",
					"collier-diamant-et-pierre-de-couleur" => "gems-and-diamond-necklace",
					"collier-diamant-et-perles" => "pearls-and-diamond-necklace",
					"bracelet-diamant" 	=> "diamond-bracelet",
					"bracelet-pierre-de-couleur" => "gems-bracelet",
					"bracelet-perles" => "pearls-bracelet",
					"bracelet-diamant-et-pierre-de-couleur" => "gems-and-diamond-bracelet",
					"bracelet-diamant-et-perles" => "pearls-and-diamond-bracelet",
					"pierre-de-couleur-et-perles" => "pearls-and-colored-stone",
					"pierre-de-couleur-et-perles" => "pearl-and-colored-stone",
					"pierre-de-couleur-et-perles" => "pearl-and-colored-stone",
					"pierre-de-couleur-et-perles" => "pearl-and-colored-stone",
					"pierre-de-couleur-et-perles" => "pearl-and-colored-stone",
					"pièce-en-or-sans-pierre" => "pieces-in-gold-without-any-stone",
                );

$fr_materials_arr = array("or-jaune" =>  "yellow-gold",
					      "or-blanc"  =>  "white-gold",
					      "or-rose" =>  "pink-gold",
					      "argent" =>  "silver",
					      "platinium" => "platinum",
					      "bi-couleur-en-or" =>  "bi-colour-with-gold",
 						  "trois-couleurs-dor" =>  "three-colour-with-gold",
 						  "métal-noir" => "black-metal",
						 );
?>